import subprocess
try:
    print("    _         _                        _            ")
    print("   / \  _   _| |_ ___  _ __ ___   __ _| |_ ___ _ __ ")
    print("  / _ \| | | | __/ _ \| '_ ` _ \ / _` | __/ _ \ '__|")
    print(" / ___ \ |_| | || (_) | | | | | | (_| | ||  __/ |   ")
    print("/_/   \_\__,_|\__\___/|_| |_| |_|\__,_|\__\___|_|   By @Kr0n0s")
    print()
    print("Installer for OS that have apt for package manager")
    print("[+] Updating repository...")
    subprocess.run("sudo apt update", shell=True)
    print("[+] Installing aircrack-ng...")
    subprocess.run("sudo apt install -y aircrack-ng", shell=True)
    print("[+] Installing nikto...")
    subprocess.run("sudo apt install -y nikto", shell=True)
    print("[+] Installing metagoofil...")
    subprocess.run("sudo apt install -y metagoofil", shell=True)
    print("[+] Installing whois...")
    subprocess.run("sudo apt install -y whois", shell=True)
except:
    print("There is some error... Quitting")
